print('What has a neck, but no head?')
input()
print('A bottle')
print()
print('What can not be used until it is broken?')
input()
print('An egg')
print()
print('Knock-knock')
input()
print('Who is there?')
input()
print('Impolite cow')
input()
print('Impolite cow?', end='')
print(' -MOOOO!')
